# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-08-21 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accountType', models.CharField(choices=[('trial', 'trial'), ('community', 'community'), ('commercial', 'commercial')], default='trial', max_length=10)),
                ('remaining', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('apiKey', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiAccountsCreatedOrOwned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApiAccountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('usageAdded', models.PositiveIntegerField(default=0)),
                ('accActive', models.BooleanField(default=True)),
                ('refID', models.CharField(max_length=50, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tools.ApiAccount')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKeyRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('email_otp', models.CharField(max_length=6, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('emailApiKey', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiresOn', models.DateField()),
                ('attachment', models.FileField(upload_to=tools.models.getToolsFilePath)),
                ('fileID', models.CharField(max_length=100)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tools.ApiAccount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileChaches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OcrModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('baseValue', models.TextField(null=True)),
                ('ocrValue', models.TextField(null=True)),
                ('userValue', models.TextField(null=True)),
            ],
        ),
    ]
