# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-08-21 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='empType',
            field=models.CharField(choices=[(b'full time', b'full time'), (b'part time', b'part time')], default=b'full time', max_length=40),
        ),
    ]
