version: "3"
   
services:
    web:
        # image: pkyad/shpl
        build:
            context: .
        container_name: shpl
        command: >
            sh -c "python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:9001"
        restart: always
        volumes:
            - ./sh:/mysite/sh
        ports:
            - "9001:9001"
        env_file:
            - ./.env.dev
        depends_on:
            - db

    
    db:
        container_name: pg_container
        image: postgres
        restart: always
        env_file:
            - ./.env.dev
        ports:
            - "5432:5432"
        volumes:
            - /home/pradeep/pgsql_sh/:/var/lib/postgresql/data
    
    
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        env_file:
            - ./.env.dev
        ports:
            - "5050:80"
    
    redis:
        image: redis:alpine
    
    celery:
        restart: always
        build:
            context: .
        command:  celery -A libreERP worker -l info
        volumes:
            - ./sh:/mysite/sh
        env_file:
            - ./.env.dev
        depends_on:
            - db
            - redis
            - web
            
volumes:
  postgres_data:

